"""predb_v1.3

Revision ID: c19c1a1b9a8f
Revises: aedad4ac3932
Create Date: 2025-04-18 11:01:41.728001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19c1a1b9a8f'
down_revision: Union[str, None] = 'aedad4ac3932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datadriver',
    sa.Column('datadriverid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('createdon', sa.DateTime(), nullable=True),
    sa.Column('modifiedon', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('datadriverid'),
    sa.UniqueConstraint('datadriverid')
    )
    op.create_table('dataparameter',
    sa.Column('dataparameterid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('nature', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('datadriver_id', sa.String(length=32), nullable=True),
    sa.Column('new_template_param_id', sa.String(length=32), nullable=True),
    sa.Column('createdon', sa.DateTime(), nullable=True),
    sa.Column('modifiedon', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('dataparameterid'),
    sa.UniqueConstraint('dataparameterid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataparameter')
    op.drop_table('datadriver')
    # ### end Alembic commands ###
